development:
  adapter: postgresql
  encoding: unicode
  database: faktura_development
  pool: 5
  username: postgres
  password: hanes123
test:
  adapter: postgresql
  encoding: unicode
  database: faktura_test
  pool: 5
  username: postgres
  password: hanes123
production:
  adapter: postgresql
  encoding: unicode
  database: faktura_production
  pool: 5
  username: faktura-api
  password:
